// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/scheduler.proto

package scheduler

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FailurePolicy int32

const (
	FailurePolicy_FAIL_FAST            FailurePolicy = 0
	FailurePolicy_SKIP_DOWNSTREAM      FailurePolicy = 1
	FailurePolicy_CONTINUE_INDEPENDENT FailurePolicy = 2
)

// Enum value maps for FailurePolicy.
var (
	FailurePolicy_name = map[int32]string{
		0: "FAIL_FAST",
		1: "SKIP_DOWNSTREAM",
		2: "CONTINUE_INDEPENDENT",
	}
	FailurePolicy_value = map[string]int32{
		"FAIL_FAST":            0,
		"SKIP_DOWNSTREAM":      1,
		"CONTINUE_INDEPENDENT": 2,
	}
)

func (x FailurePolicy) Enum() *FailurePolicy {
	p := new(FailurePolicy)
	*p = x
	return p
}

func (x FailurePolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailurePolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_scheduler_proto_enumTypes[0].Descriptor()
}

func (FailurePolicy) Type() protoreflect.EnumType {
	return &file_proto_scheduler_proto_enumTypes[0]
}

func (x FailurePolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailurePolicy.Descriptor instead.
func (FailurePolicy) EnumDescriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{0}
}

type WorkflowState int32

const (
	WorkflowState_WORKFLOW_RUNNING   WorkflowState = 0
	WorkflowState_WORKFLOW_COMPLETE  WorkflowState = 1
	WorkflowState_WORKFLOW_FAILED    WorkflowState = 2
	WorkflowState_WORKFLOW_CANCELLED WorkflowState = 3
)

// Enum value maps for WorkflowState.
var (
	WorkflowState_name = map[int32]string{
		0: "WORKFLOW_RUNNING",
		1: "WORKFLOW_COMPLETE",
		2: "WORKFLOW_FAILED",
		3: "WORKFLOW_CANCELLED",
	}
	WorkflowState_value = map[string]int32{
		"WORKFLOW_RUNNING":   0,
		"WORKFLOW_COMPLETE":  1,
		"WORKFLOW_FAILED":    2,
		"WORKFLOW_CANCELLED": 3,
	}
)

func (x WorkflowState) Enum() *WorkflowState {
	p := new(WorkflowState)
	*p = x
	return p
}

func (x WorkflowState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_scheduler_proto_enumTypes[1].Descriptor()
}

func (WorkflowState) Type() protoreflect.EnumType {
	return &file_proto_scheduler_proto_enumTypes[1]
}

func (x WorkflowState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowState.Descriptor instead.
func (WorkflowState) EnumDescriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{1}
}

type TaskState int32

const (
	TaskState_TASK_PENDING  TaskState = 0
	TaskState_TASK_QUEUED   TaskState = 1
	TaskState_TASK_RUNNING  TaskState = 2
	TaskState_TASK_COMPLETE TaskState = 3
	TaskState_TASK_FAILED   TaskState = 4
	TaskState_TASK_SKIPPED  TaskState = 5
	TaskState_TASK_UNKNOWN  TaskState = 6
)

// Enum value maps for TaskState.
var (
	TaskState_name = map[int32]string{
		0: "TASK_PENDING",
		1: "TASK_QUEUED",
		2: "TASK_RUNNING",
		3: "TASK_COMPLETE",
		4: "TASK_FAILED",
		5: "TASK_SKIPPED",
		6: "TASK_UNKNOWN",
	}
	TaskState_value = map[string]int32{
		"TASK_PENDING":  0,
		"TASK_QUEUED":   1,
		"TASK_RUNNING":  2,
		"TASK_COMPLETE": 3,
		"TASK_FAILED":   4,
		"TASK_SKIPPED":  5,
		"TASK_UNKNOWN":  6,
	}
)

func (x TaskState) Enum() *TaskState {
	p := new(TaskState)
	*p = x
	return p
}

func (x TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_scheduler_proto_enumTypes[2].Descriptor()
}

func (TaskState) Type() protoreflect.EnumType {
	return &file_proto_scheduler_proto_enumTypes[2]
}

func (x TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskState.Descriptor instead.
func (TaskState) EnumDescriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{2}
}

// Workflow submission
type TaskSpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Dependencies   []string               `protobuf:"bytes,2,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	Command        string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Env            map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	MaxRetries     int32                  `protobuf:"varint,6,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskSpec) Reset() {
	*x = TaskSpec{}
	mi := &file_proto_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSpec) ProtoMessage() {}

func (x *TaskSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSpec.ProtoReflect.Descriptor instead.
func (*TaskSpec) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *TaskSpec) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskSpec) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *TaskSpec) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *TaskSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *TaskSpec) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *TaskSpec) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

type WorkflowSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Tasks         []*TaskSpec            `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
	FailurePolicy FailurePolicy          `protobuf:"varint,3,opt,name=failure_policy,json=failurePolicy,proto3,enum=scheduler.FailurePolicy" json:"failure_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowSpec) Reset() {
	*x = WorkflowSpec{}
	mi := &file_proto_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowSpec) ProtoMessage() {}

func (x *WorkflowSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowSpec.ProtoReflect.Descriptor instead.
func (*WorkflowSpec) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *WorkflowSpec) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkflowSpec) GetTasks() []*TaskSpec {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *WorkflowSpec) GetFailurePolicy() FailurePolicy {
	if x != nil {
		return x.FailurePolicy
	}
	return FailurePolicy_FAIL_FAST
}

// Worker stream messages
type WorkerMessage struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	WorkerId string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WorkerMessage_TaskRequest
	//	*WorkerMessage_Heartbeat
	//	*WorkerMessage_TaskResult
	Payload       isWorkerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_proto_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *WorkerMessage) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerMessage) GetPayload() isWorkerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WorkerMessage) GetTaskRequest() *TaskRequest {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_TaskRequest); ok {
			return x.TaskRequest
		}
	}
	return nil
}

func (x *WorkerMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *WorkerMessage) GetTaskResult() *TaskResult {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_TaskResult); ok {
			return x.TaskResult
		}
	}
	return nil
}

type isWorkerMessage_Payload interface {
	isWorkerMessage_Payload()
}

type WorkerMessage_TaskRequest struct {
	TaskRequest *TaskRequest `protobuf:"bytes,2,opt,name=task_request,json=taskRequest,proto3,oneof"`
}

type WorkerMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type WorkerMessage_TaskResult struct {
	TaskResult *TaskResult `protobuf:"bytes,4,opt,name=task_result,json=taskResult,proto3,oneof"`
}

func (*WorkerMessage_TaskRequest) isWorkerMessage_Payload() {}

func (*WorkerMessage_Heartbeat) isWorkerMessage_Payload() {}

func (*WorkerMessage_TaskResult) isWorkerMessage_Payload() {}

type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capacity      int32                  `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *TaskRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type Heartbeat struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TimestampUnixMs int64                  `protobuf:"varint,1,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	RunningTaskIds  []string               `protobuf:"bytes,2,rep,name=running_task_ids,json=runningTaskIds,proto3" json:"running_task_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *Heartbeat) GetRunningTaskIds() []string {
	if x != nil {
		return x.RunningTaskIds
	}
	return nil
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Output        string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	DurationMs    int64                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_proto_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *TaskResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *TaskResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// Coordinator response messages
type CoordinatorMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*CoordinatorMessage_TaskAssignment
	//	*CoordinatorMessage_NoTask
	//	*CoordinatorMessage_Ping
	Payload       isCoordinatorMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorMessage) Reset() {
	*x = CoordinatorMessage{}
	mi := &file_proto_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorMessage) ProtoMessage() {}

func (x *CoordinatorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorMessage.ProtoReflect.Descriptor instead.
func (*CoordinatorMessage) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{6}
}

func (x *CoordinatorMessage) GetPayload() isCoordinatorMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CoordinatorMessage) GetTaskAssignment() *TaskAssignment {
	if x != nil {
		if x, ok := x.Payload.(*CoordinatorMessage_TaskAssignment); ok {
			return x.TaskAssignment
		}
	}
	return nil
}

func (x *CoordinatorMessage) GetNoTask() *NoTask {
	if x != nil {
		if x, ok := x.Payload.(*CoordinatorMessage_NoTask); ok {
			return x.NoTask
		}
	}
	return nil
}

func (x *CoordinatorMessage) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*CoordinatorMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isCoordinatorMessage_Payload interface {
	isCoordinatorMessage_Payload()
}

type CoordinatorMessage_TaskAssignment struct {
	TaskAssignment *TaskAssignment `protobuf:"bytes,1,opt,name=task_assignment,json=taskAssignment,proto3,oneof"`
}

type CoordinatorMessage_NoTask struct {
	NoTask *NoTask `protobuf:"bytes,2,opt,name=no_task,json=noTask,proto3,oneof"`
}

type CoordinatorMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

func (*CoordinatorMessage_TaskAssignment) isCoordinatorMessage_Payload() {}

func (*CoordinatorMessage_NoTask) isCoordinatorMessage_Payload() {}

func (*CoordinatorMessage_Ping) isCoordinatorMessage_Payload() {}

type TaskAssignment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ExecutionId    string                 `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Command        string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Env            map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskAssignment) Reset() {
	*x = TaskAssignment{}
	mi := &file_proto_scheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignment) ProtoMessage() {}

func (x *TaskAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignment.ProtoReflect.Descriptor instead.
func (*TaskAssignment) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{7}
}

func (x *TaskAssignment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAssignment) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *TaskAssignment) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *TaskAssignment) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *TaskAssignment) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type NoTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WaitMs        int32                  `protobuf:"varint,1,opt,name=wait_ms,json=waitMs,proto3" json:"wait_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoTask) Reset() {
	*x = NoTask{}
	mi := &file_proto_scheduler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoTask) ProtoMessage() {}

func (x *NoTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoTask.ProtoReflect.Descriptor instead.
func (*NoTask) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{8}
}

func (x *NoTask) GetWaitMs() int32 {
	if x != nil {
		return x.WaitMs
	}
	return 0
}

type Ping struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TimestampUnixMs int64                  `protobuf:"varint,1,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_proto_scheduler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{9}
}

func (x *Ping) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

// Status queries
type WorkflowStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId        string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	State             WorkflowState          `protobuf:"varint,2,opt,name=state,proto3,enum=scheduler.WorkflowState" json:"state,omitempty"`
	TaskStatuses      []*TaskStatus          `protobuf:"bytes,3,rep,name=task_statuses,json=taskStatuses,proto3" json:"task_statuses,omitempty"`
	SubmittedAtUnixMs int64                  `protobuf:"varint,4,opt,name=submitted_at_unix_ms,json=submittedAtUnixMs,proto3" json:"submitted_at_unix_ms,omitempty"`
	CompletedAtUnixMs int64                  `protobuf:"varint,5,opt,name=completed_at_unix_ms,json=completedAtUnixMs,proto3" json:"completed_at_unix_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WorkflowStatus) Reset() {
	*x = WorkflowStatus{}
	mi := &file_proto_scheduler_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowStatus) ProtoMessage() {}

func (x *WorkflowStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowStatus.ProtoReflect.Descriptor instead.
func (*WorkflowStatus) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{10}
}

func (x *WorkflowStatus) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkflowStatus) GetState() WorkflowState {
	if x != nil {
		return x.State
	}
	return WorkflowState_WORKFLOW_RUNNING
}

func (x *WorkflowStatus) GetTaskStatuses() []*TaskStatus {
	if x != nil {
		return x.TaskStatuses
	}
	return nil
}

func (x *WorkflowStatus) GetSubmittedAtUnixMs() int64 {
	if x != nil {
		return x.SubmittedAtUnixMs
	}
	return 0
}

func (x *WorkflowStatus) GetCompletedAtUnixMs() int64 {
	if x != nil {
		return x.CompletedAtUnixMs
	}
	return 0
}

type TaskStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	State         TaskState              `protobuf:"varint,2,opt,name=state,proto3,enum=scheduler.TaskState" json:"state,omitempty"`
	AttemptCount  int32                  `protobuf:"varint,3,opt,name=attempt_count,json=attemptCount,proto3" json:"attempt_count,omitempty"`
	Output        string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatus) Reset() {
	*x = TaskStatus{}
	mi := &file_proto_scheduler_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatus) ProtoMessage() {}

func (x *TaskStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatus.ProtoReflect.Descriptor instead.
func (*TaskStatus) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{11}
}

func (x *TaskStatus) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskStatus) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_TASK_PENDING
}

func (x *TaskStatus) GetAttemptCount() int32 {
	if x != nil {
		return x.AttemptCount
	}
	return 0
}

func (x *TaskStatus) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *TaskStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SubmitWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitWorkflowResponse) Reset() {
	*x = SubmitWorkflowResponse{}
	mi := &file_proto_scheduler_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitWorkflowResponse) ProtoMessage() {}

func (x *SubmitWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitWorkflowResponse.ProtoReflect.Descriptor instead.
func (*SubmitWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{12}
}

func (x *SubmitWorkflowResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *SubmitWorkflowResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitWorkflowResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetWorkflowStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowStatusRequest) Reset() {
	*x = GetWorkflowStatusRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowStatusRequest) ProtoMessage() {}

func (x *GetWorkflowStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowStatusRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{13}
}

func (x *GetWorkflowStatusRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type CancelWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelWorkflowRequest) Reset() {
	*x = CancelWorkflowRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWorkflowRequest) ProtoMessage() {}

func (x *CancelWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWorkflowRequest.ProtoReflect.Descriptor instead.
func (*CancelWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{14}
}

func (x *CancelWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type CancelWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelWorkflowResponse) Reset() {
	*x = CancelWorkflowResponse{}
	mi := &file_proto_scheduler_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWorkflowResponse) ProtoMessage() {}

func (x *CancelWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWorkflowResponse.ProtoReflect.Descriptor instead.
func (*CancelWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{15}
}

func (x *CancelWorkflowResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelWorkflowResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_scheduler_proto protoreflect.FileDescriptor

const file_proto_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x15proto/scheduler.proto\x12\tscheduler\"\x93\x02\n" +
	"\bTaskSpec\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\"\n" +
	"\fdependencies\x18\x02 \x03(\tR\fdependencies\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12.\n" +
	"\x03env\x18\x04 \x03(\v2\x1c.scheduler.TaskSpec.EnvEntryR\x03env\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x12\x1f\n" +
	"\vmax_retries\x18\x06 \x01(\x05R\n" +
	"maxRetries\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9b\x01\n" +
	"\fWorkflowSpec\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12)\n" +
	"\x05tasks\x18\x02 \x03(\v2\x13.scheduler.TaskSpecR\x05tasks\x12?\n" +
	"\x0efailure_policy\x18\x03 \x01(\x0e2\x18.scheduler.FailurePolicyR\rfailurePolicy\"\xe4\x01\n" +
	"\rWorkerMessage\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12;\n" +
	"\ftask_request\x18\x02 \x01(\v2\x16.scheduler.TaskRequestH\x00R\vtaskRequest\x124\n" +
	"\theartbeat\x18\x03 \x01(\v2\x14.scheduler.HeartbeatH\x00R\theartbeat\x128\n" +
	"\vtask_result\x18\x04 \x01(\v2\x15.scheduler.TaskResultH\x00R\n" +
	"taskResultB\t\n" +
	"\apayload\")\n" +
	"\vTaskRequest\x12\x1a\n" +
	"\bcapacity\x18\x01 \x01(\x05R\bcapacity\"a\n" +
	"\tHeartbeat\x12*\n" +
	"\x11timestamp_unix_ms\x18\x01 \x01(\x03R\x0ftimestampUnixMs\x12(\n" +
	"\x10running_task_ids\x18\x02 \x03(\tR\x0erunningTaskIds\"\xb1\x01\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\"\xba\x01\n" +
	"\x12CoordinatorMessage\x12D\n" +
	"\x0ftask_assignment\x18\x01 \x01(\v2\x19.scheduler.TaskAssignmentH\x00R\x0etaskAssignment\x12,\n" +
	"\ano_task\x18\x02 \x01(\v2\x11.scheduler.NoTaskH\x00R\x06noTask\x12%\n" +
	"\x04ping\x18\x03 \x01(\v2\x0f.scheduler.PingH\x00R\x04pingB\t\n" +
	"\apayload\"\xfd\x01\n" +
	"\x0eTaskAssignment\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x124\n" +
	"\x03env\x18\x04 \x03(\v2\".scheduler.TaskAssignment.EnvEntryR\x03env\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"!\n" +
	"\x06NoTask\x12\x17\n" +
	"\await_ms\x18\x01 \x01(\x05R\x06waitMs\"2\n" +
	"\x04Ping\x12*\n" +
	"\x11timestamp_unix_ms\x18\x01 \x01(\x03R\x0ftimestampUnixMs\"\xff\x01\n" +
	"\x0eWorkflowStatus\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12.\n" +
	"\x05state\x18\x02 \x01(\x0e2\x18.scheduler.WorkflowStateR\x05state\x12:\n" +
	"\rtask_statuses\x18\x03 \x03(\v2\x15.scheduler.TaskStatusR\ftaskStatuses\x12/\n" +
	"\x14submitted_at_unix_ms\x18\x04 \x01(\x03R\x11submittedAtUnixMs\x12/\n" +
	"\x14completed_at_unix_ms\x18\x05 \x01(\x03R\x11completedAtUnixMs\"\xa4\x01\n" +
	"\n" +
	"TaskStatus\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12*\n" +
	"\x05state\x18\x02 \x01(\x0e2\x14.scheduler.TaskStateR\x05state\x12#\n" +
	"\rattempt_count\x18\x03 \x01(\x05R\fattemptCount\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"i\n" +
	"\x16SubmitWorkflowResponse\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\";\n" +
	"\x18GetWorkflowStatusRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"8\n" +
	"\x15CancelWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"H\n" +
	"\x16CancelWorkflowResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error*M\n" +
	"\rFailurePolicy\x12\r\n" +
	"\tFAIL_FAST\x10\x00\x12\x13\n" +
	"\x0fSKIP_DOWNSTREAM\x10\x01\x12\x18\n" +
	"\x14CONTINUE_INDEPENDENT\x10\x02*i\n" +
	"\rWorkflowState\x12\x14\n" +
	"\x10WORKFLOW_RUNNING\x10\x00\x12\x15\n" +
	"\x11WORKFLOW_COMPLETE\x10\x01\x12\x13\n" +
	"\x0fWORKFLOW_FAILED\x10\x02\x12\x16\n" +
	"\x12WORKFLOW_CANCELLED\x10\x03*\x88\x01\n" +
	"\tTaskState\x12\x10\n" +
	"\fTASK_PENDING\x10\x00\x12\x0f\n" +
	"\vTASK_QUEUED\x10\x01\x12\x10\n" +
	"\fTASK_RUNNING\x10\x02\x12\x11\n" +
	"\rTASK_COMPLETE\x10\x03\x12\x0f\n" +
	"\vTASK_FAILED\x10\x04\x12\x10\n" +
	"\fTASK_SKIPPED\x10\x05\x12\x10\n" +
	"\fTASK_UNKNOWN\x10\x062\xd2\x02\n" +
	"\tScheduler\x12L\n" +
	"\x0eSubmitWorkflow\x12\x17.scheduler.WorkflowSpec\x1a!.scheduler.SubmitWorkflowResponse\x12S\n" +
	"\x11GetWorkflowStatus\x12#.scheduler.GetWorkflowStatusRequest\x1a\x19.scheduler.WorkflowStatus\x12U\n" +
	"\x0eCancelWorkflow\x12 .scheduler.CancelWorkflowRequest\x1a!.scheduler.CancelWorkflowResponse\x12K\n" +
	"\fWorkerStream\x12\x18.scheduler.WorkerMessage\x1a\x1d.scheduler.CoordinatorMessage(\x010\x01B?Z=github.com/aakashkolli/dag-scheduler/internal/proto/schedulerb\x06proto3"

var (
	file_proto_scheduler_proto_rawDescOnce sync.Once
	file_proto_scheduler_proto_rawDescData []byte
)

func file_proto_scheduler_proto_rawDescGZIP() []byte {
	file_proto_scheduler_proto_rawDescOnce.Do(func() {
		file_proto_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scheduler_proto_rawDesc), len(file_proto_scheduler_proto_rawDesc)))
	})
	return file_proto_scheduler_proto_rawDescData
}

var file_proto_scheduler_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_scheduler_proto_goTypes = []any{
	(FailurePolicy)(0),               // 0: scheduler.FailurePolicy
	(WorkflowState)(0),               // 1: scheduler.WorkflowState
	(TaskState)(0),                   // 2: scheduler.TaskState
	(*TaskSpec)(nil),                 // 3: scheduler.TaskSpec
	(*WorkflowSpec)(nil),             // 4: scheduler.WorkflowSpec
	(*WorkerMessage)(nil),            // 5: scheduler.WorkerMessage
	(*TaskRequest)(nil),              // 6: scheduler.TaskRequest
	(*Heartbeat)(nil),                // 7: scheduler.Heartbeat
	(*TaskResult)(nil),               // 8: scheduler.TaskResult
	(*CoordinatorMessage)(nil),       // 9: scheduler.CoordinatorMessage
	(*TaskAssignment)(nil),           // 10: scheduler.TaskAssignment
	(*NoTask)(nil),                   // 11: scheduler.NoTask
	(*Ping)(nil),                     // 12: scheduler.Ping
	(*WorkflowStatus)(nil),           // 13: scheduler.WorkflowStatus
	(*TaskStatus)(nil),               // 14: scheduler.TaskStatus
	(*SubmitWorkflowResponse)(nil),   // 15: scheduler.SubmitWorkflowResponse
	(*GetWorkflowStatusRequest)(nil), // 16: scheduler.GetWorkflowStatusRequest
	(*CancelWorkflowRequest)(nil),    // 17: scheduler.CancelWorkflowRequest
	(*CancelWorkflowResponse)(nil),   // 18: scheduler.CancelWorkflowResponse
	nil,                              // 19: scheduler.TaskSpec.EnvEntry
	nil,                              // 20: scheduler.TaskAssignment.EnvEntry
}
var file_proto_scheduler_proto_depIdxs = []int32{
	19, // 0: scheduler.TaskSpec.env:type_name -> scheduler.TaskSpec.EnvEntry
	3,  // 1: scheduler.WorkflowSpec.tasks:type_name -> scheduler.TaskSpec
	0,  // 2: scheduler.WorkflowSpec.failure_policy:type_name -> scheduler.FailurePolicy
	6,  // 3: scheduler.WorkerMessage.task_request:type_name -> scheduler.TaskRequest
	7,  // 4: scheduler.WorkerMessage.heartbeat:type_name -> scheduler.Heartbeat
	8,  // 5: scheduler.WorkerMessage.task_result:type_name -> scheduler.TaskResult
	10, // 6: scheduler.CoordinatorMessage.task_assignment:type_name -> scheduler.TaskAssignment
	11, // 7: scheduler.CoordinatorMessage.no_task:type_name -> scheduler.NoTask
	12, // 8: scheduler.CoordinatorMessage.ping:type_name -> scheduler.Ping
	20, // 9: scheduler.TaskAssignment.env:type_name -> scheduler.TaskAssignment.EnvEntry
	1,  // 10: scheduler.WorkflowStatus.state:type_name -> scheduler.WorkflowState
	14, // 11: scheduler.WorkflowStatus.task_statuses:type_name -> scheduler.TaskStatus
	2,  // 12: scheduler.TaskStatus.state:type_name -> scheduler.TaskState
	4,  // 13: scheduler.Scheduler.SubmitWorkflow:input_type -> scheduler.WorkflowSpec
	16, // 14: scheduler.Scheduler.GetWorkflowStatus:input_type -> scheduler.GetWorkflowStatusRequest
	17, // 15: scheduler.Scheduler.CancelWorkflow:input_type -> scheduler.CancelWorkflowRequest
	5,  // 16: scheduler.Scheduler.WorkerStream:input_type -> scheduler.WorkerMessage
	15, // 17: scheduler.Scheduler.SubmitWorkflow:output_type -> scheduler.SubmitWorkflowResponse
	13, // 18: scheduler.Scheduler.GetWorkflowStatus:output_type -> scheduler.WorkflowStatus
	18, // 19: scheduler.Scheduler.CancelWorkflow:output_type -> scheduler.CancelWorkflowResponse
	9,  // 20: scheduler.Scheduler.WorkerStream:output_type -> scheduler.CoordinatorMessage
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_scheduler_proto_init() }
func file_proto_scheduler_proto_init() {
	if File_proto_scheduler_proto != nil {
		return
	}
	file_proto_scheduler_proto_msgTypes[2].OneofWrappers = []any{
		(*WorkerMessage_TaskRequest)(nil),
		(*WorkerMessage_Heartbeat)(nil),
		(*WorkerMessage_TaskResult)(nil),
	}
	file_proto_scheduler_proto_msgTypes[6].OneofWrappers = []any{
		(*CoordinatorMessage_TaskAssignment)(nil),
		(*CoordinatorMessage_NoTask)(nil),
		(*CoordinatorMessage_Ping)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scheduler_proto_rawDesc), len(file_proto_scheduler_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scheduler_proto_goTypes,
		DependencyIndexes: file_proto_scheduler_proto_depIdxs,
		EnumInfos:         file_proto_scheduler_proto_enumTypes,
		MessageInfos:      file_proto_scheduler_proto_msgTypes,
	}.Build()
	File_proto_scheduler_proto = out.File
	file_proto_scheduler_proto_goTypes = nil
	file_proto_scheduler_proto_depIdxs = nil
}
